
services:
  backend:
    build:
      context: ./rxpill-backend
      dockerfile: Dockerfile
    container_name: rxpill-backend
    ports:
      - "${BACKEND_PORT}:3000"
    env_file: .env
    depends_on:
      - postgres
      - redis
    networks:
      - rxpill-net

  frontend:
    build:
      context: ./rxpill-frontend
      dockerfile: Dockerfile
    container_name: rxpill-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - rxpill-net

  postgres:
    image: postgres:16
    container_name: rxpill-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rxpill-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - rxpill-net

  redis:
    image: redis:7
    container_name: rxpill-redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - rxpill-net

networks:
  rxpill-net:

volumes:
  pgdata:
