name: CI/CD

on:
  pull_request:
    branches: [ main ]

jobs:
  run-checks:
    name: Setup and Building Project
    runs-on: ubuntu-latest

    if: startsWith(github.head_ref, 'feat/') || startsWith(github.head_ref, 'fix/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install backend dependencies
        working-directory: rxpill-backend
        run: pnpm install --frozen-lockfile

      - name: Install frontend dependencies
        working-directory: rxpill-frontend
        run: pnpm install --frozen-lockfile

      - name: Build Backend
        working-directory: rxpill-backend
        run: pnpm build

      - name: Build Frontend
        working-directory: rxpill-frontend
        run: pnpm build
